service: serverless-coding-challenge

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2

custom:
  userInfoTable: userInfoTable

functions:
  verifyUser:
    handler: verify.handler
    events:
      - http:
          path: users/verify
          method: get
          cors: true

resources:
  Resources:
    UserInfoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: UserID
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: UserID
            KeyType: HASH
        TableName: ${self:custom.userInfoTable}
